on:
  push:
  branches:
   - 'main'  
workflows:
  angular-backoffice:
    name: Angular Back Office
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      groups:
        - google_play # (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS <-- Put your google-services.json)
      vars:
        PACKAGE_NAME: "io.codemagic.sample.angular" # <-- Put your package name here e.g. com.domain.myapp
      node: v19.7.0
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build Angular app
        script: |
          npm run build -- --prod
      - name: Prepare Android build
        script: |
          cd android
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Build Android release
        script: |
          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME")
          if [ -z "$LATEST_GOOGLE_PLAY_BUILD_NUMBER" ]; then
            # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
            UPDATED_BUILD_NUMBER=$BUILD_NUMBER
          else
            UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
          fi
          ./gradlew bundleRelease \
            -PversionCode=$UPDATED_BUILD_NUMBER \
            -PversionName=1.0.$UPDATED_BUILD_NUMBER
      - name: Prepare iOS build
        script: |
          cd ios
          pod install
      - name: Build iOS release
        script: |
          xcodebuild \
            -workspace MyApp.xcworkspace \
            -scheme MyApp \
            -sdk iphoneos \
            -configuration AppStoreDistribution \
            -archivePath $CM_BUILD_DIR/MyApp.xcarchive \
            archive
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/MyApp.xcarchive \
            -exportPath $CM_BUILD_DIR/MyApp.ipa \
            -exportOptionsPlist ExportOptions.plist
    artifacts:
      - android/app/build/outputs/**/*.aab
      - $CM_BUILD_DIR/MyApp.ipa
      - dist/**/* # Artifacts for the web build
    publishing:
      email:
        recipients:
          - simeon.philippesaintantoine@diiage.org
          - cameron.desrayaud@diiage.org
        notify:
          success: true
          failure: false
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: alpha
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        key_id: $APP_STORE_CONNECT_KEY
