name: Deploy Angular App to Azure Static Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step to check out the source code
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Step to set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.x'

    # Step to install Angular CLI globally
    - name: Install Angular CLI
      run: npm install -g @angular/cli

    # Step to install project dependencies
    - name: Install dependencies
      run: npm ci

    # Step to build the Angular app with prod configuration
    - name: Build Angular app
      run: ng build

    # Step to copy the static web app configuration (if necessary)
    - name: Copy staticwebapp.config.json
      run: cp swa-cli.config.json ./dist/back_office

    # Step to install the Azure Static Web Apps CLI
    - name: Install Azure Static Web Apps CLI
      run: npm install -g @azure/static-web-apps-cli

    # Step to deploy the app using the Azure Static Web Apps CLI
    - name: Deploy to Azure Static Web Apps
      run: swa deploy ./dist/back_office --deployment-token ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
